using AutoMapper;
using iLoveIbadah.Application.DTOs.BlobFile;
using iLoveIbadah.Application.DTOs.Blog;
using iLoveIbadah.Application.DTOs.BlogCategoryMapping;
using iLoveIbadah.Application.DTOs.BlogLike;
using iLoveIbadah.Application.DTOs.BlogTagMapping;
using iLoveIbadah.Application.DTOs.Category;
using iLoveIbadah.Application.DTOs.Comment;
using iLoveIbadah.Application.DTOs.CommentLike;
using iLoveIbadah.Application.DTOs.DhikrType;
using iLoveIbadah.Application.DTOs.PermissionType;
using iLoveIbadah.Application.DTOs.ProfilePictureType;
using iLoveIbadah.Application.DTOs.RoleType;
using iLoveIbadah.Application.DTOs.RoleTypePermissionTypeMapping;
using iLoveIbadah.Application.DTOs.SalahType;
using iLoveIbadah.Application.DTOs.Tag;
using iLoveIbadah.Application.DTOs.UserAccount;
using iLoveIbadah.Application.DTOs.UserAccountRoleTypeMapping;
using iLoveIbadah.Application.DTOs.UserDhikrActivity;
using iLoveIbadah.Application.DTOs.UserDhikrOverview;
using iLoveIbadah.Application.DTOs.UserSalahActivity;
using iLoveIbadah.Application.DTOs.UserSalahOverview;
using iLoveIbadah.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace iLoveIbadah.Application.Profiles
{
    // Map Entities to Dtos, Application Layer to Domain Layer
    public class MappingProfile : Profile
    {
        public MappingProfile()
        {
            CreateMap<Blog, BlogDto>().ReverseMap();
            CreateMap<Blog, BlogListDto>().ReverseMap();
            CreateMap<Blog, CreateBlogDto>().ReverseMap();
            CreateMap<Blog, UpdateBlogDto>().ReverseMap();
            CreateMap<BlogCategoryMapping, CreateBlogCategoryMappingDto>().ReverseMap();
            CreateMap<BlogLike, CreateBlogLikeDto>().ReverseMap();
            CreateMap<BlogTagMapping, CreateBlogTagMappingDto>().ReverseMap();
            CreateMap<Category, CategoryDto>().ReverseMap();
            CreateMap<Category, CategoryListDto>().ReverseMap();
            CreateMap<Category, CreateCategoryDto>().ReverseMap();
            CreateMap<Category, UpdateCategoryDto>().ReverseMap();
            CreateMap<Comment, CommentDto>().ReverseMap();
            CreateMap<Comment, CommentListDto>().ReverseMap();
            CreateMap<Comment, CreateCommentDto>().ReverseMap();
            CreateMap<Comment, UpdateCommentDto>().ReverseMap();
            CreateMap<CommentLike, CreateCommentLikeDto>().ReverseMap();
            CreateMap<Tag, TagDto>().ReverseMap();
            CreateMap<Tag, TagListDto>().ReverseMap();
            CreateMap<Tag, CreateTagDto>().ReverseMap();
            CreateMap<Tag, UpdateTagDto>().ReverseMap();
            CreateMap<BlobFile, BlobFileDto>().ReverseMap();
            CreateMap<BlobFile, BlobFileListDto>().ReverseMap();
            CreateMap<BlobFile, CreateBlobFileDto>().ReverseMap();
            CreateMap<DhikrType, DhikrTypeListDto>().ReverseMap();
            CreateMap<DhikrType, DhikrTypeDto>().ReverseMap();
            CreateMap<DhikrType, CreateDhikrTypeDto>().ReverseMap();
            CreateMap<DhikrType, DhikrTypeByUserAccountListDto>().ReverseMap();
            CreateMap<SalahType, SalahTypeDto>().ReverseMap();
            CreateMap<SalahType, SalahTypeListDto>().ReverseMap();
            CreateMap<ProfilePictureType, ProfilePictureTypeDto>().ReverseMap();
            CreateMap<ProfilePictureType, ProfilePictureTypeListDto>().ReverseMap();
            CreateMap<RoleType, RoleTypeDto>().ReverseMap();
            CreateMap<RoleType, RoleTypeListDto>().ReverseMap();
            CreateMap<PermissionType, PermissionTypeDto>().ReverseMap();
            CreateMap<PermissionType, PermissionTypeListDto>().ReverseMap();
            CreateMap<RoleTypePermissionTypeMapping, RoleTypePermissionTypeMappingDto>().ReverseMap();
            CreateMap<RoleTypePermissionTypeMapping, RoleTypePermissionTypeMappingListDto>().ReverseMap();
            CreateMap<UserAccount, UserAccountDto>().ReverseMap();
            CreateMap<UserAccount, UserAccountListDto>().ReverseMap();
            CreateMap<UserAccount, CreateUserAccountDto>().ReverseMap();
            CreateMap<UserAccount, UpdateUserAccountDto>().ReverseMap();
            CreateMap<UserAccount, UpdateUserAccountCurrentLocationDto>().ReverseMap();
            CreateMap<UserAccount, UpdateUserAccountEmailConfirmedDto>().ReverseMap();
            CreateMap<UserAccount, UpdateUserAccountIsPermanentlyBannedDto>().ReverseMap();
            CreateMap<UserAccount, UpdateUserAccountPasswordHashDto>().ReverseMap();
            CreateMap<UserAccount, UpdateUserAccountTotalWarningsDto>().ReverseMap();
            CreateMap<UserAccountRoleTypeMapping, UserAccountRoleTypeMappingDto>().ReverseMap();
            CreateMap<UserAccountRoleTypeMapping, UserAccountRoleTypeMappingListDto>().ReverseMap();
            CreateMap<UserDhikrActivity, UserDhikrActivityDto>().ReverseMap();
            CreateMap<UserDhikrActivity, UserDhikrActivityListDto>().ReverseMap();
            CreateMap<UserDhikrActivity, CreateUserDhikrActivityDto>().ReverseMap();
            CreateMap<UserDhikrActivity, UpdateUserDhikrActivityDto>().ReverseMap();
            CreateMap<UserDhikrOverview, UserDhikrOverviewDto>().ReverseMap();
            CreateMap<UserDhikrOverview, UserDhikrOverviewListDto>().ReverseMap();
            CreateMap<UserDhikrActivity, UserDhikrActivityByPerformedOnDto>().ReverseMap();
            CreateMap<UserSalahActivity, UserSalahActivityListDto>().ReverseMap();
            CreateMap<UserSalahActivity, UserSalahActivityListByTrackedOnDto>().ReverseMap();
            CreateMap<UserSalahActivity, UserSalahActivityDto>().ReverseMap();
            CreateMap<UserSalahActivity, CreateUserSalahActivityDto>().ReverseMap();
            CreateMap<UserSalahActivity, UpdateUserSalahActivityDto>().ReverseMap();
            CreateMap<UserSalahOverview, UserSalahOverviewDto>().ReverseMap();
            CreateMap<UserSalahOverview, UserSalahOverviewListDto>().ReverseMap();
        }
    }
}
